### ISSUE TITLE
Support for projects not ready to upgrade to Kotlin 1.4

### ISSUE THREAD

**Issue by 1951FDG** [AppDevNext/Logcat#143]
@hannesa2,

The idea would be to not use Kotlin 1.4 language features to keep Kotlin 1.3 library APIs
The benefit is that depending clients do not have to upgrade to Kotlin 1.4

Right now I'm still stuck on v2.1.1, because I'm not ready to update to Kotlin 1.4.

LeakCanary does this well, see:

[LeakCanary build.gradle file](https://github.com/square/leakcanary/blob/main/build.gradle)

I would be willing to implement this, if you agree I can start working on this, and also fix some of the issues open, and open a pull request for you to review. Also once I implement this, I can also commit other changes that I may find beneficial.

Thanks!

**Comment by hannesa2** [comment]
Ok, you want to have a `ext.kotlin_version = '1.3.xx'`  ?
If it helps you, I'm fine with it. But what must happen, to skip this stay-on-old-Kotlin ? I just searching for a exit strategy.

Independent of this, what's about a Kotlin 1.3 branch with own releases, and master still on most recent ones ?

**Comment by 1951FDG** [comment]
One idea is to move to `1.4.xx` once `1.4.xx` reaches final version, the question more or less is when to migrate from one version to the next

In the LeakCanary example, kotlin-gradle-plugin and kotlin compiler is at `1.4.xx`, kotlin lib is at `1.3.xx`, so it stays up to date with both Android Studio and latest Kotlin compiler is used

```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
      // Avoid warnings of using older stdlib version 1.3 than compiler version 1.4
      apiVersion = "1.3"
    }
  }
```

The disadvantages would be not having access to `1.4` language features in the meantime

I was also looking at [Moshi](https://github.com/square/moshi), because their latest release worked in a `1.3.72` project even though they use `1.4.20`

+--- com.squareup.moshi:moshi:1.12.0
|    +--- com.squareup.okio:okio:2.10.0
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.20 -> 1.3.72 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.20 -> 1.3.72

The only thing that I can think of is that they don't use `1.4` language features somehow ( I can't see anything special in their gradle files) 

Another thing we could try:

https://kotlinlang.org/docs/gradle.html#attributes-common-for-jvm-and-js

languageVersion | Provide source compatibility with the specified version of Kotlin | "1.2" (DEPRECATED), "1.3", "1.4", "1.5" (EXPERIMENTAL)
-- | -- | --

I haven't tested this, maybe adding the following could work:

```
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
      languageVersion = "1.3"
    }
  }
```

Also note the  "1.2" (DEPRECATED) above in the table, maybe when "1.3" (DEPRECATED) we move to "1.4"?

I'm just thinking of options here, the different branches I can't recommend, two code bases, and having to keep them at sync, other library maintainers struggle or let the other branch go completely stale.

Options:

1. SquareCanary example, it is enforced
2. Moshi example, not enforced?,  carefully not use `1.4` language features even in included dependencies, to be honest I don't know how they achieve `1.3` compatibility simply using `1.4` libs
3. Test the `languageVersion` feature, which seems the most promising feature, that way lib would be at '1.4' but would support `1.3` as well, assuming code compiled is `1.3` compatible and maybe use `1.4` features
4. Another branch just to keep Kotlin at a different version

To be honest, I find this a very interesting subject matter, where some library devs push latest Kotlin, where some support older Kotlin while doing so, the different ways to go about it, everything is also very bleeding edge nowadays, if you want the latest update of many but not all ktx libraries may also depend on `1.4`, so I'm keen to hear your thoughts on this subject matter, maybe we can come to some conclusion of sorts...

**Comment by hannesa2** [comment]
I don't want to make a science out of it and keep it as simple as possible.

Currently there is no reason to have different code bases, it build with 1.3 out of the box #144
It's easy to revert with this pull request, but on the other side I don't want to stuck on old versions.
I can't measure when it's fine, to go with 1.4 again or even with up coming 1.5

Theoretically, someone want s to have 1.2 ,an other guy 1.3, 1.4, 1.5 ..... we can't support any historical version.

The thing is, you can't upgrade because of some reasons outside of this repository, am I right ?
Why should be this a cascading blocker, isn't it better to solve it on the source ? And there is a version in this repo `2.1.1` supporting Kotlin 1.3.x.

But I want to help you !

Currently I like the way of https://github.com/Triple-T/gradle-play-publisher/releases/tag/3.3.0 to support older versions (till I see a better solution)

And to be honest, who make pull requests changes the system

**Comment by 1951FDG** [comment]
Ok, wait, don't merge #144.

I think I can manage to keep the lib at 1.4.xx while still supporting 1.3.xx, I'll work on this next week and open a pull request soon!

The idea would be to stay backwards compatible one version only, e.g. once 1.5.xx is stable enough or at lastest version then for example we would be able to start using 1.4 languages not deprecated in 1.5.xx

I found this related article,

https://proandroiddev.com/kotlin-library-development-for-android-java-hints-29365017516d

**Comment by 1951FDG** [comment]
I've created a pull request, which actually fixes a bunch of other things...

**Comment by 1951FDG** [comment]
I think we can close this as well

**Comment by 1951FDG** [comment]
Adding this last note for those who want to use the newest version of the lib in a Kotlin 1.3.xx project:

To avoid build failure due to higher version of `kotlinx-coroutines-android` (you are then responsible for loading the excluded required dependencies)

```groovy
implementation('com.github.AppDevNext.Logcat:LogcatCore:2.6.0') {
    exclude group: 'androidx.lifecycle'
    exclude group: 'org.jetbrains.kotlin'
    exclude group: 'org.jetbrains.kotlinx'
}
```

**Comment by hannesa2** [comment]
Thank you, if you see space for improvements... go ahead

https://github.com/AppDevNext/Logcat/commit/d25e247166df5c18e72d3b0598c56b8501acc22b
