### ISSUE TITLE
Suggestion, add log level to lastLogEntry

### ISSUE THREAD

**Issue by 1951FDG** [AppDevNext/Logcat#55]
Right now only a string is specified, better would be a data class containing both string and log level

Currently, changing the way the text is displayed, for example if I want to start a line with `I/` instead of `I: `  or textually omit the level is not possible,

https://github.com/AppDevNext/Logcat/blob/3de29e8db09403a017fdf5666eb16306f66feba3/LogcatLib/src/main/java/info/hannes/logcat/base/LogListAdapter.kt#L78-L94

**Comment by hannesa2** [comment]
I'm open minded about it, but as I understand, when it catches from `adb logcat` directly, it has to work with strings only

**Comment by 1951FDG** [comment]
I forgot that the library also supports Logcat, I suppose the strings could be parsed for level info?

**Comment by 1951FDG** [comment]
I think we can close this
